# Generated by Django 5.2.4 on 2026-09-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.CharField(default='Maurya Technical Team', max_length=100)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(default='info@mauryatechnical.com', max_length=254)),
                ('is_head_office', models.BooleanField(default=False)),
                ('map_embed_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('course_name', models.CharField(max_length=200)),
                ('training_duration', models.CharField(default='6 Months', max_length=100)),
                ('issue_date', models.DateField()),
                ('grade', models.CharField(default='A+', max_length=20)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('course_taken', models.CharField(default='Python with Django', max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('designation', models.CharField(default='Software Engineer', max_length=150)),
                ('package', models.CharField(default='4.5 LPA', max_length=50)),
                ('student_image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('placed_year', models.IntegerField(default=2026)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('college', models.CharField(max_length=200)),
                ('branch', models.CharField(help_text='e.g. CS, IT, BCA, MCA, Diploma', max_length=100)),
                ('year_of_study', models.CharField(default='3rd Year', max_length=50)),
                ('course_interested', models.CharField(max_length=150)),
                ('training_type', models.CharField(choices=[('winter_2026', 'Winter Training 2026'), ('summer_2026', 'Summer Training 2026'), ('6_months', '6 Months Industrial Training'), ('45_days', '45 Days Project Training'), ('online_batch', 'Online Live Batch')], default='winter_2026', max_length=50)),
                ('city', models.CharField(default='Lucknow', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('tech_stack', models.CharField(help_text='e.g. Full Stack Developer / Python Trainer', max_length=200)),
                ('bio', models.TextField()),
                ('phone', models.CharField(default='9198483820', max_length=20)),
                ('email', models.EmailField(default='info@mauryatechnical.com', max_length=254)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(default='Software Development', max_length=100)),
                ('duration', models.CharField(choices=[('6_weeks', '06 Weeks / 45 Days'), ('6_months', '06 Months Industrial Training'), ('both', '45 Days & 06 Months')], default='both', max_length=50)),
                ('badge_text', models.CharField(default='WINTER TRAINING 2026', max_length=100)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField(blank=True)),
                ('features', models.TextField(default='100% Job Oriented, Live Project, Industry Experts', help_text='Comma separated key features')),
                ('image_url', models.CharField(blank=True, help_text='Image URL or static path', max_length=500, null=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
