# Generated by Django 5.2.4 on 2026-09-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='fee_45_days',
            field=models.CharField(default='₹4,000', help_text='Fee for 45 Days / 6 Weeks', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='fee_6_months',
            field=models.CharField(default='₹18,000', help_text='Fee for 06 Months Industrial Training', max_length=50),
        ),
    ]
