# Generated by Django 5.2.4 on 2026-09-15 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trainingcourse_fee_45_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(help_text='Unique Faculty ID e.g. MT101 or MT-FAC-2026', max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('designation', models.CharField(default='Senior Technical Trainer', max_length=150)),
                ('department', models.CharField(default='Computer Science & IT', max_length=100)),
                ('qualification', models.CharField(default='B.Tech, M.Tech', max_length=200)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('phone', models.CharField(default='+91 88582 98247', max_length=20)),
                ('email', models.EmailField(default='faculty@mauryatechnical.in', max_length=254)),
                ('photo', models.CharField(blank=True, default='/static/images/director_vivek_kushawaha.png', max_length=500, null=True)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=45000.0, max_digits=10)),
                ('bank_name', models.CharField(default='State Bank of India', max_length=100)),
                ('account_number', models.CharField(default='XXXXXXXX4582', max_length=50)),
                ('ifsc_code', models.CharField(default='SBIN0001234', max_length=30)),
                ('pan_number', models.CharField(default='ABCDE1234F', max_length=20)),
                ('blood_group', models.CharField(default='B+', max_length=10)),
                ('emergency_contact', models.CharField(default='+91 7080838689', max_length=50)),
                ('assigned_batches', models.TextField(blank=True, default='Python Full-Stack (10:00 AM - 12:00 PM), Data Analytics (02:00 PM - 04:00 PM)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(help_text='e.g. February 2026', max_length=50)),
                ('pay_date', models.DateField(default=django.utils.timezone.now)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=30000.0, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=8000.0, max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=7000.0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=1800.0, max_digits=10)),
                ('tds_deduction', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=42700.0, max_digits=10)),
                ('payment_mode', models.CharField(default='Bank Transfer (NEFT)', max_length=50)),
                ('transaction_id', models.CharField(default='TXN-MT-202602-8858', max_length=100)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending Processing')], default='paid', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='core.faculty')),
            ],
            options={
                'ordering': ['-pay_date'],
            },
        ),
        migrations.CreateModel(
            name='FacultyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'Approved Leave'), ('holiday', 'Holiday / Sunday')], default='present', max_length=20)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.faculty')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('faculty', 'date')},
            },
        ),
    ]
